import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'app.dart';

class IntegratedApp extends StatelessWidget {
  const IntegratedApp({super.key});
  @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Master Trading Engine',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.amber,brightness:Brightness.dark),home:const IntegratedHome());
}

class IntegratedHome extends StatelessWidget { const IntegratedHome({super.key});
  @override Widget build(BuildContext context)=>DefaultTabController(length:4,child:Scaffold(appBar:AppBar(title:const Text('MASTER TRADING ENGINE'),actions:[Padding(padding:const EdgeInsets.all(8),child:Chip(avatar:const Icon(Icons.lock,size:16),label:const Text('AUTO-TRADING LOCKED')))],bottom:const TabBar(tabs:[Tab(icon:Icon(Icons.analytics),text:'Live AI'),Tab(icon:Icon(Icons.science),text:'Backtest'),Tab(icon:Icon(Icons.account_balance_wallet),text:'Paper'),Tab(icon:Icon(Icons.security),text:'Safety')])),body:const TabBarView(children:[Dashboard(),BacktestPage(),PaperPage(),SafetyPage()])));
}

class BacktestPage extends StatefulWidget { const BacktestPage({super.key}); @override State<BacktestPage> createState()=>_BacktestPageState(); }
class _BacktestPageState extends State<BacktestPage>{final prices=TextEditingController(text:'100\n101\n102\n101\n103\n104\n102\n105');final capital=TextEditingController(text:'100000');double finalCapital=100000,dd=0;int trades=0,wins=0;
void run(){final p=prices.text.split(RegExp(r'[\n,]+')).map(double.tryParse).whereType<double>().where((x)=>x>0).toList();final initial=double.tryParse(capital.text)??0;if(initial<=0||p.length<2)return;var cash=initial,peak=initial;double? entry;String? side;var n=0,w=0;for(var i=1;i<p.length;i++){final x=p[i];if(entry==null){if(x>p[i-1]){entry=x;side='LONG';}else if(x<p[i-1]){entry=x;side='SHORT';}}else{final pnl=side=='LONG'?(x-entry!):(entry!-x);final close=(side=='LONG'?(x>=entry!*1.02||x<=entry!*.99):(x<=entry!*.98||x>=entry!*1.01))||i==p.length-1;if(close){cash+=pnl;n++;if(pnl>0)w++;entry=null;side=null;}}final eq=cash+(entry==null?0:(side=='LONG'?x-entry!:(entry!-x)));peak=math.max(peak,eq);dd=math.max(dd,peak-eq);}setState(()=>{finalCapital=cash;trades=n;wins=w;});}
@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Historical Backtest',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:10),TextField(controller:capital,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Initial Capital',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:prices,minLines:6,maxLines:12,decoration:const InputDecoration(labelText:'Close prices',border:OutlineInputBorder())),const SizedBox(height:10),FilledButton.icon(onPressed:run,icon:const Icon(Icons.play_arrow),label:const Text('RUN BACKTEST')),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:[_m('Final','₹${finalCapital.toStringAsFixed(2)}'),_m('Net P&L','₹${(finalCapital-(double.tryParse(capital.text)??0)).toStringAsFixed(2)}'),_m('Trades','$trades'),_m('Win Rate',trades==0?'0%':'${(wins/trades*100).toStringAsFixed(1)}%'),_m('Max DD','₹${dd.toStringAsFixed(2)}')]),const SizedBox(height:10),const Text('Simulation only. Historical results do not guarantee future performance.')]);}
Widget _m(String a,String b)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:Colors.white60)),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))])));
}

class PaperPage extends StatefulWidget{const PaperPage({super.key});@override State<PaperPage> createState()=>_PaperPageState();}
class _PaperPageState extends State<PaperPage>{final price=TextEditingController(text:'100');bool running=false,killed=false;double cash=100000,realized=0;double? entry;int trades=0;String status='Waiting';
void tick(){final p=double.tryParse(price.text);if(!running||killed||p==null||p<=0)return;setState((){if(entry==null){entry=p;status='OPEN LONG @ ${p.toStringAsFixed(2)}';return;}final pnl=p-entry!;if(p>=entry!*1.02||p<=entry!*.99){cash+=pnl;realized+=pnl;trades++;status='CLOSED @ ${p.toStringAsFixed(2)} | P&L ₹${pnl.toStringAsFixed(2)}';entry=null;}else{status='HOLD LONG @ ${entry!.toStringAsFixed(2)} | LTP ${p.toStringAsFixed(2)}';}});}
void close(){final p=double.tryParse(price.text);if(entry==null||p==null)return;setState((){final pnl=p-entry!;cash+=pnl;realized+=pnl;trades++;status='MANUAL CLOSE | P&L ₹${pnl.toStringAsFixed(2)}';entry=null;});}
@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[const Text('Paper Trading Simulator',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('Virtual execution only. No broker order is sent.'),const SizedBox(height:12),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Market Price',border:OutlineInputBorder())),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:[FilledButton(onPressed:killed?null:()=>setState(()=>running=true),child:const Text('START')),OutlinedButton(onPressed:()=>setState(()=>running=false),child:const Text('PAUSE')),OutlinedButton(onPressed:running&&!killed?tick:null,child:const Text('PROCESS TICK')),OutlinedButton(onPressed:entry!=null?close:null,child:const Text('CLOSE')),FilledButton.tonal(onPressed:()=>setState(()=>{killed=true;running=false;}),child:const Text('KILL SWITCH'))]),const SizedBox(height:10),Card(child:ListTile(title:const Text('Last Action'),subtitle:Text(status))),Wrap(spacing:8,children:[_m('Virtual Cash','₹${cash.toStringAsFixed(2)}'),_m('Realized P&L','₹${realized.toStringAsFixed(2)}'),_m('Trades','$trades'),_m('Position',entry==null?'None':'LONG @ ${entry!.toStringAsFixed(2)}')])]);}
Widget _m(String a,String b)=>Card(child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(color:Colors.white60)),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))])));
}

class SafetyPage extends StatelessWidget{const SafetyPage({super.key});@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:const[Card(child:ListTile(leading:Icon(Icons.lock),title:Text('Auto-Trading'),subtitle:Text('LOCKED'))),Card(child:ListTile(leading:Icon(Icons.block),title:Text('Real Broker Orders'),subtitle:Text('DISABLED'))),Card(child:ListTile(leading:Icon(Icons.account_balance_wallet),title:Text('Execution'),subtitle:Text('Paper / Virtual only'))),Card(child:ListTile(leading:Icon(Icons.shield),title:Text('Risk Gate'),subtitle:Text('Trade suggestions require setup validation')))]);}}
