import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

const bg = Color(0xFF050A11);
const panel = Color(0xFF0A111B);
const gold = Color(0xFFE7AD2F);
const green = Color(0xFF27D86B);
const red = Color(0xFFFF4B4B);
const blue = Color(0xFF20A7FF);

class Candle { final double o,h,l,c,v; const Candle(this.o,this.h,this.l,this.c,this.v); }
class Analysis {
  final String regime,direction,psychology; final int score,buyer,seller; final double rsi,ema20,ema50,ema200,atr,support,resistance,fair; final bool trend,breakout;
  const Analysis({required this.regime,required this.direction,required this.psychology,required this.score,required this.buyer,required this.seller,required this.rsi,required this.ema20,required this.ema50,required this.ema200,required this.atr,required this.support,required this.resistance,required this.fair,required this.trend,required this.breakout});
}

class IntegratedApp extends StatefulWidget { const IntegratedApp({super.key}); @override State<IntegratedApp> createState()=>_IntegratedAppState(); }
class _IntegratedAppState extends State<IntegratedApp> {
  final symbol=TextEditingController(text:'BTCUSDT'); String interval='15m',status='ENGINE SYNC',error=''; bool live=true,loading=false; Timer? timer; List<Candle> candles=[]; Analysis? analysis; int page=0;
  final nav=const ['Dashboard','Live Market','AI Analysis','AI Chat','AI Strategy','Backtest','Paper Trading','Portfolio','Trade Journal','Alerts','Reports','Settings'];
  @override void initState(){super.initState();refresh();timer=Timer.periodic(const Duration(seconds:15),(_){if(live)refresh();});}
  @override void dispose(){timer?.cancel();symbol.dispose();super.dispose();}
  Future<void> refresh()async{if(loading)return;setState(()=>loading=true);try{final s=symbol.text.trim().toUpperCase();final uri=Uri.parse('https://api.binance.com/api/v3/klines?symbol=$s&interval=$interval&limit=200');final r=await http.get(uri).timeout(const Duration(seconds:8));if(r.statusCode!=200)throw Exception('HTTP ${r.statusCode}');final raw=jsonDecode(r.body) as List;final d=raw.map((x)=>Candle(double.parse(x[1].toString()),double.parse(x[2].toString()),double.parse(x[3].toString()),double.parse(x[4].toString()),double.parse(x[5].toString()))).toList();if(!mounted)return;setState((){candles=d;analysis=analyze(d);status='ENGINE LIVE';error='';});}catch(e){if(mounted)setState((){status='FEED ERROR';error='Market feed error: $e';});}finally{if(mounted)setState(()=>loading=false);}}
  void setLive(bool v){setState(()=>live=v);if(v)refresh();}
  @override Widget build(BuildContext context){return MaterialApp(debugShowCheckedModeBanner:false,title:'Master Trading Engine',theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,scaffoldBackgroundColor:bg,colorScheme:const ColorScheme.dark(primary:gold)),home:Scaffold(body:Row(children:[if(MediaQuery.sizeOf(context).width>=900)_sidebar(),Expanded(child:SafeArea(child:_content()))])));}
  Widget _sidebar()=>Container(width:190,color:const Color(0xFF070D15),child:Column(children:[const SizedBox(height:20),const Text('MASTER TRADING',style:TextStyle(color:gold,fontWeight:FontWeight.bold)),const Text('LIVE MARKET INTELLIGENCE',style:TextStyle(fontSize:8,color:Colors.white60)),const SizedBox(height:18),Expanded(child:ListView.builder(itemCount:nav.length,itemBuilder:(_,i)=>ListTile(dense:true,selected:i==page,selectedTileColor:const Color(0xFF211A0D),title:Text(nav[i],style:TextStyle(color:i==page?gold:Colors.white70,fontSize:11)),onTap:()=>setState(()=>page=i)))),const Padding(padding:EdgeInsets.all(14),child:Row(children:[Icon(Icons.circle,color:green,size:8),SizedBox(width:6),Text('CONNECTION LIVE',style:TextStyle(fontSize:9,color:Colors.white70))]))]));
  Widget _content(){if(page!=0)return Center(child:Text('${nav[page]} module',style:const TextStyle(color:gold,fontSize:22,fontWeight:FontWeight.bold)));final a=analysis;return RefreshIndicator(onRefresh:refresh,color:gold,child:ListView(padding:const EdgeInsets.all(12),children:[_header(),if(error.isNotEmpty)_errorCard(),const SizedBox(height:10),_summary(a),const SizedBox(height:10),_chart(),const SizedBox(height:10),if(a!=null)_analysisGrid(a)else _panel('TRADE ENGINE',const Text('Waiting for connected market data...',style:TextStyle(color:Colors.white54))),const SizedBox(height:10),_actions()]));}
  Widget _header()=>Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('MASTER TRADING ENGINE',style:TextStyle(color:gold,fontSize:20,fontWeight:FontWeight.w900)),Text('LIVE MARKET INTELLIGENCE · ENGINE CONNECTED',style:TextStyle(color:Colors.white60,fontSize:9))])),SizedBox(width:105,child:TextField(controller:symbol,onSubmitted:(_)=>refresh(),style:const TextStyle(fontSize:10),decoration:const InputDecoration(isDense:true,labelText:'Market',border:OutlineInputBorder()))),const SizedBox(width:6),DropdownButton<String>(value:interval,items:const ['1m','5m','15m','1h','4h','1d'].map((e)=>DropdownMenuItem(value:e,child:Text(e))).toList(),onChanged:(v){if(v!=null){setState(()=>interval=v);refresh();}}),IconButton(onPressed:loading?null:refresh,icon:const Icon(Icons.refresh,color:gold)),FilterChip(selected:live,onSelected:setLive,label:Text(live?'● LIVE':'○ LIVE OFF',style:const TextStyle(fontSize:9)))]);
  Widget _errorCard()=>Card(child:ListTile(leading:const Icon(Icons.warning,color:red),title:const Text('Market feed error'),subtitle:Text(error)));
  Widget _summary(Analysis? a)=>LayoutBuilder(builder:(_,c){final n=c.maxWidth>=800?5:2;return GridView.count(crossAxisCount:n,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:2.25,children:[_card('MARKET',a==null?'--':fmt(a.ema20),'BTC/USDT',gold),_card('REGIME',a?.regime??'--','Engine detection',green),_card('DIRECTION',a?.direction??'--',a==null?'Waiting':'${a.score}% confidence',a?.direction=='SHORT'?red:green),_card('VOLATILITY',a==null?'--':'${(a.atr/math.max(1,a.ema20)*100).toStringAsFixed(2)}%','ATR (14)',gold),_card('TIMEFRAME',interval.toUpperCase(),status,gold)]);});
  Widget _card(String t,String v,String s,Color c)=>Card(color:panel,child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisAlignment:MainAxisAlignment.center,children:[Text(t,style:const TextStyle(color:Colors.white70,fontSize:9)),const SizedBox(height:4),Text(v,style:TextStyle(color:c,fontSize:17,fontWeight:FontWeight.w900)),Text(s,style:const TextStyle(color:Colors.white54,fontSize:8))])));
  Widget _chart()=>Card(color:panel,child:Padding(padding:const EdgeInsets.all(9),child:Column(children:[Row(children:[Text('${symbol.text.toUpperCase()} · ${interval.toUpperCase()} · BINANCE',style:const TextStyle(fontSize:10,fontWeight:FontWeight.bold)),const Spacer(),Text(status,style:TextStyle(color:status=='ENGINE LIVE'?green:red,fontSize:9,fontWeight:FontWeight.bold))]),const SizedBox(height:8),SizedBox(height:330,child:candles.isEmpty?const Center(child:Text('Loading connected market feed...')):CustomPaint(painter:CandlePainter(candles)))])));
  Widget _analysisGrid(Analysis a)=>LayoutBuilder(builder:(_,c){final n=c.maxWidth>=900?2:1;return GridView.count(crossAxisCount:n,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:9,mainAxisSpacing:9,childAspectRatio:1.65,children:[_setup(a),_factors(a),_fair(a),_levels(a),_sentiment(a),_copilot(a)]);});
  Widget _setup(Analysis a)=>_panel('TRADE SETUP',Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a.direction=='NEUTRAL'?'WAIT':a.direction=='LONG'?'BUY ↗':'SELL ↘',style:TextStyle(color:a.direction=='SHORT'?red:green,fontSize:24,fontWeight:FontWeight.w900)),_kv('Reference',fmt(a.ema20)),_kv('Stop reference',fmt(a.direction=='LONG'?a.ema20-a.atr*1.2:a.ema20+a.atr*1.2),red),_kv('Target reference',fmt(a.direction=='LONG'?a.ema20+a.atr*2:a.ema20-a.atr*2),green),_kv('Confidence','${a.score}%',green)]));
  Widget _factors(Analysis a)=>_panel('MARKET FACTORS · 12',Column(children:List.generate(12,(i){const names=['Trend','Regime','Structure','Momentum','Volume','Volatility','Support/Resistance','Fair Value','Pattern','Risk/Reward','Liquidity','Session'];final values=[a.trend?88:55,a.breakout?90:75,82,a.rsi.round().clamp(0,100),75,70,85,80,70,78,75,80];final v=values[i];return Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Row(children:[SizedBox(width:105,child:Text(names[i],style:const TextStyle(fontSize:8))),Expanded(child:LinearProgressIndicator(value:v/100,minHeight:5,backgroundColor:const Color(0xFF283241),color:v>=70?green:gold)),const SizedBox(width:6),Text('$v%',style:const TextStyle(fontSize:8))]));})));
  Widget _fair(Analysis a)=>_panel('FAIR VALUE ANALYSIS',Column(children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text('Fair Value\n${fmt(a.fair)}'),Text('Reference\n${fmt(a.ema20)}',textAlign:TextAlign.right)]),const SizedBox(height:12),LinearProgressIndicator(value:((a.ema20-a.support)/math.max(1,a.resistance-a.support)).clamp(0.0,1.0),minHeight:8,color:gold,backgroundColor:const Color(0xFF303944)),const SizedBox(height:8),Text(a.fair<=a.ema20?'Near / below fair-value reference':'Above fair-value reference',style:const TextStyle(color:Colors.white70,fontSize:9))]));
  Widget _levels(Analysis a)=>_panel('KEY LEVELS',Column(children:[_kv('Resistance',fmt(a.resistance),red),_kv('Fair Value',fmt(a.fair),gold),_kv('Support',fmt(a.support),blue),_kv('ATR',fmt(a.atr),gold)]));
  Widget _sentiment(Analysis a)=>_panel('MARKET SENTIMENT',Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('BUYERS ${a.buyer}% · SELLERS ${a.seller}%',style:TextStyle(color:a.buyer>=50?green:red,fontSize:13,fontWeight:FontWeight.bold)),const SizedBox(height:7),LinearProgressIndicator(value:a.buyer/100,minHeight:7,color:green,backgroundColor:red),const SizedBox(height:5),Text(a.buyer>=55?'Bullish':a.buyer<=45?'Bearish':'Neutral',style:const TextStyle(color:Colors.white60,fontSize:9))]));
  Widget _copilot(Analysis a)=>_panel('AI MARKET COPILOT',Text('Market regime: ${a.regime}. Direction: ${a.direction}. RSI ${a.rsi.toStringAsFixed(1)}, EMA20 ${fmt(a.ema20)}, EMA50 ${fmt(a.ema50)}, EMA200 ${fmt(a.ema200)}. This dashboard provides analysis and paper-trading information only.',style:const TextStyle(color:Colors.white70,fontSize:9,height:1.5)));
  Widget _actions()=>GridView.count(crossAxisCount:MediaQuery.sizeOf(context).width>=900?6:3,shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisSpacing:8,mainAxisSpacing:8,childAspectRatio:2.3,children:['AI Trade','AI Chat','AI Strategy','Backtest','Paper Trading','Alerts'].map((s)=>Card(color:panel,child:Center(child:Text(s,style:const TextStyle(color:gold,fontWeight:FontWeight.bold,fontSize:10)))).toList());
  Widget _panel(String t,Widget child)=>Card(color:panel,child:Padding(padding:const EdgeInsets.all(11),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:gold,fontSize:9,fontWeight:FontWeight.bold)),const SizedBox(height:8),child])));
  Widget _kv(String k,String v,[Color? c])=>Padding(padding:const EdgeInsets.symmetric(vertical:3),child:Row(children:[Expanded(child:Text(k,style:const TextStyle(color:Colors.white60,fontSize:9))),Text(v,style:TextStyle(color:c??Colors.white,fontSize:9,fontWeight:FontWeight.bold))]));
}

double fmt(double v)=>v.abs()>=1000?v.toStringAsFixed(2):v.toStringAsFixed(4);

Analysis analyze(List<Candle> c){
  if(c.length<3)return const Analysis(regime:'WAITING',direction:'NEUTRAL',psychology:'Waiting for enough market data.',score:0,buyer:50,seller:50,rsi:50,ema20:0,ema50:0,ema200:0,atr:0,support:0,resistance:0,fair:0,trend:false,breakout:false);
  final close=c.map((x)=>x.c).toList(),high=c.map((x)=>x.h).toList(),low=c.map((x)=>x.l).toList();
  double ema(int n){var e=close.first;final k=2/(n+1);for(final p in close.skip(1)){e=p*k+e*(1-k);}return e;}
  final e20=ema(20),e50=ema(50),e200=ema(200),n=math.min(14,close.length-1);var gain=0.0,loss=0.0,tr=0.0;
  for(var i=close.length-n;i<close.length;i++){final d=close[i]-close[i-1];if(d>=0){gain+=d;}else{loss-=d;}tr+=math.max(c[i].h-c[i].l,math.max((c[i].h-c[i-1].c).abs(),(c[i].l-c[i-1].c).abs()));}
  final rsi=loss==0?100.0:100-(100/(1+gain/loss)),atr=tr/n,start=math.max(0,c.length-21),support=low.sublist(start).reduce(math.min),resistance=high.sublist(start).reduce(math.max),last=close.last;
  final bull=e20>e50&&e50>e200&&last>e20&&rsi>=52,bear=e20<e50&&e50<e200&&last<e20&&rsi<=48,breakout=last>resistance||last<support,direction=(bull||last>resistance)?'LONG':(bear||last<support)?'SHORT':'NEUTRAL',trend=bull||bear,regime=breakout?'BREAKOUT':trend?'TREND':'RANGE';
  var score=35;if(trend){score+=20;}if(breakout){score+=20;}if(direction=='NEUTRAL'){score=math.min(score,59);}score=math.min(score,100);final buyer=math.max(5,math.min(95,(50+(rsi-50)*1.4+(bull?18:0)+(breakout&&direction=='LONG'?12:0)).round()));final psychology=direction=='LONG'?'Buyers have structural control; confirmation and pullback risk should be monitored.':direction=='SHORT'?'Sellers have structural control; confirmation and rebound risk should be monitored.':'No clean participant edge. Avoid forcing a setup.';
  return Analysis(regime:regime,direction:direction,psychology:psychology,score:score,buyer:buyer,seller:100-buyer,rsi:rsi,ema20:e20,ema50:e50,ema200:e200,atr:atr,support:support,resistance:resistance,fair:e20,trend:trend,breakout:breakout);
}

class CandlePainter extends CustomPainter { final List<Candle> data; CandlePainter(this.data); @override void paint(Canvas canvas,Size size){final n=math.min(80,data.length),d=data.sublist(data.length-n),hi=d.map((x)=>x.h).reduce(math.max),lo=d.map((x)=>x.l).reduce(math.min),range=hi==lo?1.0:hi-lo,w=size.width/n;final paint=Paint()..strokeWidth=1.2;double y(double v)=>size.height-(v-lo)/range*size.height;for(var i=0;i<n;i++){final k=d[i],x=i*w+w/2;paint.color=k.c>=k.o?Colors.greenAccent:Colors.redAccent;canvas.drawLine(Offset(x,y(k.h)),Offset(x,y(k.l)),paint);final top=y(math.max(k.o,k.c)),bottom=y(math.min(k.o,k.c));canvas.drawRect(Rect.fromLTWH(x-w*.3,top,w*.6,math.max(1,bottom-top)),paint);}}@override bool shouldRepaint(covariant CandlePainter oldDelegate)=>oldDelegate.data!=data;}
